---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "vcenter_server"
    vcenter_user: "vcenter_user"
    vcenter_pass: "vcenter_pass"
    datacenter_name: "ZeusDC"
    cluster_name: "Cluster01"
  tasks:
  - debug: var=vcenter_user

  - name: Clone VM from Template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: web02
      template: venkat-ubuntu
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "CLRM_INFRA"
      state: poweredon
    delegate_to: localhost

  - name: Customize
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: web02
      networks:
      - name: pgVLAN141
        ip: 10.1.19.80
        netmask: 255.255.192.0
        gateway: 10.1.0.1
        type: static
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost

    #- name: Poweroff the VM
    #vmware_guest:
    # hostname: "{{ vcenter_server }}"
    # username: "{{ vcenter_user }}"
    # password: "{{ vcenter_pass }}"
    # validate_certs: False
    # name: web02
    # state: poweredoff
    # wait_for_ip_address: yes
    #delegate_to: localhost

